### GENERAL SETTINGS ###

# Site settings
title: Nathan Butt
description: "A lone programmers humble portfolio."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://n86-64.github.io/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator:  <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: flase
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/n86-64
  - title: linkedin
    url: https://www.linkedin.com/in/nathan-butt/
  - title: envelope #use for email address
    url: mailto:Nathan2.Butt@live.uwe.ac.uk


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Bristol, BS16 1QY,
    - United Kingdom.
email: Nathan2.Butt@live.uwe.ac.uk

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Nathan Butt
    position: Games Tech Student
    text:
    img: profile.JPG
    social:
      - title: envelope #use for email address
        url: mailto:Nathan2.Butt@live.uwe.ac.uk

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "A humble software engineer with a keen desire to learn and explore."

# Paginate splits blog listings into multiple pages.
paginate: 5
